import os
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path
S=Path('scripts/verify.sh').read_text()
class VerifyContract(unittest.TestCase):
 def test_aggregate_checks(self):
  for x in ('PASS: %s','FAIL: %s','Podman >= 4.9.3','Headscale exactly 0.29.3','container exact ownership','explicit container healthcheck','exact Serve listeners','no temporary enrollment artifacts'): self.assertIn(x,S)
  self.assertIn('failures=$((failures+1))',S); self.assertIn('(( failures == 0 )) || exit 1',S)
 def test_read_only_live_inspection(self):
  self.assertIn('podman healthcheck run "$C"',S); self.assertNotIn('podman restart',S); self.assertNotIn('systemctl --user restart',S)
 def test_nonsecret_evidence(self):
  self.assertIn('last-verification.json',S); self.assertIn("'self_id':self_id",S); self.assertNotIn("'serve':serve",S)
 def test_aggregate_runs_late_checks_after_early_failures(self):
  with tempfile.TemporaryDirectory() as directory:
   root=Path(directory)/'checkout'; (root/'scripts').mkdir(parents=True); (root/'runtime').mkdir(mode=0o700)
   for name in ('verify.sh','gateway_config.py','resource_ownership.py','headscale_json.py','image_id.py','secret_scan.py'):
    shutil.copy2(Path('scripts')/name,root/'scripts'/name)
   fake=Path(directory)/'bin'; fake.mkdir()
   for name in ('podman','systemctl','curl','journalctl'):
    path=fake/name; path.write_text('#!/bin/sh\nexit 1\n'); path.chmod(0o755)
   result=subprocess.run(['bash','scripts/verify.sh'],cwd=root,text=True,capture_output=True,env={**os.environ,'PATH':f"{fake}:{os.environ['PATH']}",'HOME':str(Path(directory)/'home')})
   self.assertNotEqual(result.returncode,0)
   combined=result.stdout+result.stderr
   self.assertIn('FAIL: strict gateway configuration',combined)
   self.assertIn('FAIL: Headscale health',combined)
   self.assertIn('no key material in repository/runtime/inspect/unit/journal',combined)
   evidence=__import__('json').loads((root/'runtime/last-verification.json').read_text())
   self.assertGreater(evidence['failures'],5)
 def test_podman_49_bare_image_and_prefixed_container_ids_match(self):
  with tempfile.TemporaryDirectory() as directory:
   root=Path(directory)/'checkout'; (root/'scripts').mkdir(parents=True); (root/'runtime').mkdir(mode=0o700)
   for name in ('verify.sh','gateway_config.py','resource_ownership.py','headscale_json.py','image_id.py','secret_scan.py'):
    shutil.copy2(Path('scripts')/name,root/'scripts'/name)
   home=Path(directory)/'home'; units=home/'.config/systemd/user'; units.mkdir(parents=True)
   image_id='0123456789abcdef'*4
   unit=units/'woow-tailscale-gateway.service'
   unit.write_text('# Generated by woow-tailscale-gateway; do not edit.\nExecStart=/usr/bin/podman run '+image_id+'\n'); unit.chmod(0o600)
   fake=Path(directory)/'bin'; fake.mkdir()
   podman=fake/'podman'; podman.write_text("""#!/usr/bin/env python3
import json,os,sys
a=sys.argv[1:]; image_id='0123456789abcdef'*4
if a[:2]==['image','inspect']:
 print(json.dumps([{'Id':image_id,'Labels':{'org.woow-tailscale.project':'woow-tailscale-gateway','org.woow-tailscale.role':'image','org.woow-tailscale.managed-by':'woow-gateway-lifecycle','org.woow-tailscale.checkout':os.environ['CHECKOUT']}}])); raise SystemExit(0)
if a[:2]==['container','inspect']:
 print(json.dumps([{'Image':'sha256:'+image_id}])); raise SystemExit(0)
raise SystemExit(1)
"""); podman.chmod(0o755)
   for name in ('systemctl','curl','journalctl'):
    path=fake/name; path.write_text('#!/bin/sh\nexit 1\n'); path.chmod(0o755)
   result=subprocess.run(['bash','scripts/verify.sh'],cwd=root,text=True,capture_output=True,env={**os.environ,'PATH':f"{fake}:{os.environ['PATH']}",'HOME':str(home),'CHECKOUT':str(root)})
   self.assertNotEqual(result.returncode,0)
   self.assertIn('PASS: unit immutable image identity',result.stdout)
   self.assertIn('PASS: running immutable image identity',result.stdout)
if __name__=='__main__': unittest.main()
