import json
import os
import shutil
import subprocess
import tempfile
import textwrap
import unittest
from pathlib import Path
S=Path('scripts/remove.sh').read_text()
class RemoveContract(unittest.TestCase):
 def test_modes_and_confirmations(self):
  self.assertIn('--retain-state',S); self.assertIn('--purge-state',S); self.assertIn('--confirm-purge',S)
  self.assertIn('--delete-headscale-node',S); self.assertIn('--confirm-node-delete',S)
 def test_exact_resources_and_ownership_first(self):
  self.assertIn('resource_ownership.py check-container',S); self.assertIn('resource_ownership.py check-volume',S)
  self.assertLess(S.index('refusing foreign image'),S.index('systemctl --user disable'))
  self.assertIn('headscale --force nodes delete --identifier "$node"',S)
  self.assertNotIn('headscale nodes delete --identifier',S)
  self.assertLess(S.index('headscale --force nodes delete'),S.index('assert-node-id-absent'))
  self.assertNotIn('podman rm -a',S); self.assertNotIn('systemctl --user disable --now *',S)
 def test_unrelated_snapshot(self):
  self.assertIn('unrelated container state changed',S); self.assertIn("'health'",S)
 def test_stop_and_container_removal_errors_fail_without_deleting_unit(self):
  with tempfile.TemporaryDirectory() as directory:
   root=Path(directory)/'checkout'; (root/'scripts').mkdir(parents=True); (root/'runtime').mkdir(mode=0o700)
   for name in ('remove.sh','resource_ownership.py','headscale_json.py','gateway_config.py'): shutil.copy2(Path('scripts')/name,root/'scripts'/name)
   home=Path(directory)/'home'; unit=home/'.config/systemd/user/woow-tailscale-gateway.service'; unit.parent.mkdir(parents=True)
   unit.write_text('# Generated by woow-tailscale-gateway; do not edit.\n'+str(root)+'\n'); unit.chmod(0o600)
   fake=Path(directory)/'bin'; fake.mkdir(); log=Path(directory)/'commands'
   systemctl=fake/'systemctl'; systemctl.write_text(textwrap.dedent('''#!/bin/sh
printf 'systemctl %s\\n' "$*" >>"$COMMAND_LOG"
case "$*" in *'show -p FragmentPath'*) [ ! -e "$UNIT_PATH" ] || printf '%s\\n' "$UNIT_PATH";; *'disable --now'*) exit 9;; esac
''')); systemctl.chmod(0o755)
   podman=fake/'podman'; podman.write_text(textwrap.dedent('''#!/bin/sh
printf 'podman %s\\n' "$*" >>"$COMMAND_LOG"
case "$*" in 'container inspect woow-tailscale-gateway'|'volume inspect woow-tailscale-gateway-state'|'image inspect localhost/woow-tailscale-gateway:latest') echo 'no such object' >&2;exit 1;; 'ps -aq') exit 0;; *) exit 2;; esac
''')); podman.chmod(0o755)
   env={**os.environ,'PATH':f"{fake}:{os.environ['PATH']}",'HOME':str(home),'COMMAND_LOG':str(log),'UNIT_PATH':str(unit),'XDG_RUNTIME_DIR':directory}
   result=subprocess.run(['bash','scripts/remove.sh','--retain-state'],cwd=root,text=True,capture_output=True,env=env)
   self.assertNotEqual(result.returncode,0); self.assertTrue(unit.exists()); self.assertNotIn('podman rm -f',log.read_text())

   # With no unit, an exact-owned container rm error is also fatal and remains untouched.
   unit.unlink(); log.unlink(); labels={'org.woow-tailscale.project':'woow-tailscale-gateway','org.woow-tailscale.role':'gateway','org.woow-tailscale.managed-by':'woow-gateway-lifecycle','org.woow-tailscale.checkout':str(root)}
   podman.write_text(textwrap.dedent(f'''#!/usr/bin/env python3
import json,os,sys
with open(os.environ['COMMAND_LOG'],'a') as f:f.write('podman '+' '.join(sys.argv[1:])+'\\n')
a=sys.argv[1:]
obj={{'Id':'gateway-id','Name':'/woow-tailscale-gateway','Labels':{labels!r},'Mounts':[{{'Destination':'/var/lib/tailscale','Name':'woow-tailscale-gateway-state'}}],'State':{{'Running':True}}}}
if a[:2]==['container','inspect']:
 if '--format' in a: print('gateway-id')
 else: print(json.dumps([obj]))
 raise SystemExit(0)
if a[:2]==['volume','inspect'] or a[:2]==['image','inspect']: print('no such object',file=sys.stderr);raise SystemExit(1)
if a[:2]==['ps','-aq']: print('gateway-id');raise SystemExit(0)
if a and a[0]=='inspect': print(json.dumps([obj]));raise SystemExit(0)
if a[:2]==['rm','-f']: raise SystemExit(7)
raise SystemExit(2)
''')); podman.chmod(0o755)
   result=subprocess.run(['bash','scripts/remove.sh','--retain-state'],cwd=root,text=True,capture_output=True,env=env)
   self.assertNotEqual(result.returncode,0); self.assertIn('podman rm -f woow-tailscale-gateway',log.read_text())
if __name__=='__main__': unittest.main()
