#!/usr/bin/env python3
"""Render and validate the exact generated gateway systemd unit."""
import argparse
import os
import shlex
from pathlib import Path

try:
    from image_id import normalize_image_id
except ModuleNotFoundError:  # Support importing this file as scripts.gateway_unit in tests.
    from scripts.image_id import normalize_image_id

LEGACY_IMAGE = "localhost/woow-tailscale-gateway:latest"


def template_source(template: Path) -> str:
    source = template.read_text()
    if source.count("@CHECKOUT@") < 1 or source.count("@IMAGE@") != 1:
        raise ValueError("gateway unit template placeholders are invalid")
    return source


def rendered(template: Path, checkout: str, image: str, allow_legacy: bool = False) -> str:
    if not (allow_legacy and image == LEGACY_IMAGE):
        image = normalize_image_id(image)
    return template_source(template).replace("@CHECKOUT@", checkout).replace("@IMAGE@", image)


def image_from_unit(unit: Path) -> str:
    starts = [line for line in unit.read_text().splitlines() if line.startswith("ExecStart=") and line != "ExecStart="]
    if len(starts) != 1:
        raise ValueError("gateway unit must have exactly one ExecStart")
    words = shlex.split(starts[0].removeprefix("ExecStart="))
    if not words or Path(words[0]).name != "podman" or len(words) < 3 or words[1] != "run":
        raise ValueError("gateway unit ExecStart is not podman run")
    image = words[-1]
    if image != LEGACY_IMAGE:
        normalize_image_id(image)
    return image


def main() -> None:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="command", required=True)
    render = sub.add_parser("render")
    render.add_argument("template", type=Path)
    render.add_argument("output", type=Path)
    render.add_argument("checkout")
    render.add_argument("image")
    check = sub.add_parser("check")
    check.add_argument("unit", type=Path)
    check.add_argument("template", type=Path)
    check.add_argument("checkout")
    args = parser.parse_args()
    if args.command == "render":
        data = rendered(args.template, args.checkout, args.image)
        fd = os.open(args.output, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(fd, "w") as destination:
            destination.write(data)
    else:
        image = image_from_unit(args.unit)
        actual = args.unit.read_text()
        expected = rendered(args.template, args.checkout, image, allow_legacy=True)
        if actual != expected:
            # Accept the exact output generated by older releases long enough to
            # replace its prefixed ID with the canonical bare ID during deploy.
            old_prefixed = (
                template_source(args.template)
                .replace("@CHECKOUT@", args.checkout)
                .replace("@IMAGE@", image)
            )
            if not image.startswith("sha256:") or actual != old_prefixed:
                raise ValueError("gateway unit differs from the exact generated contract")
        print(image if image == LEGACY_IMAGE else normalize_image_id(image))


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError) as error:
        print(f"gateway unit check failed: {error}", file=__import__("sys").stderr)
        raise SystemExit(1)
