#!/usr/bin/env bash
set -euo pipefail
umask 077
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"; cd "$ROOT"
purge=false; delete_node=false
while (($#)); do case "$1" in --retain-state) ;; --purge-state) purge=true;; --confirm-purge) confirm_purge=true;; --delete-headscale-node) delete_node=true;; --confirm-node-delete) confirm_node=true;; *) echo "unknown option: $1" >&2; exit 2;; esac; shift; done
[[ "$purge" == false || "${confirm_purge:-false}" == true ]] || { echo '--purge-state requires --confirm-purge' >&2; exit 2; }
[[ "$delete_node" == false || "${confirm_node:-false}" == true ]] || { echo '--delete-headscale-node requires --confirm-node-delete' >&2; exit 2; }
if [[ "${WOOW_GATEWAY_LOCK_HELD:-0}" != 1 ]]; then exec 9>"${XDG_RUNTIME_DIR:-$ROOT/runtime}/woow-tailscale-gateway.lock"; flock -x 9; export WOOW_GATEWAY_LOCK_HELD=1; fi
python3 scripts/resource_ownership.py check-container "$ROOT" --allow-absent
python3 scripts/resource_ownership.py check-volume "$ROOT" --allow-absent
unit="$HOME/.config/systemd/user/woow-tailscale-gateway.service"
if [[ -e "$unit" ]]; then [[ -f "$unit" && ! -L "$unit" ]] && grep -Fxq '# Generated by woow-tailscale-gateway; do not edit.' "$unit" && grep -Fq "$ROOT" "$unit" || { echo 'refusing foreign gateway unit' >&2; exit 1; }; fi
fragment="$(systemctl --user show -p FragmentPath --value woow-tailscale-gateway.service 2>/dev/null || true)"
[[ -z "$fragment" || "$fragment" == "$unit" ]] || { echo 'refusing foreign loaded gateway unit' >&2; exit 1; }
installed_env="$HOME/.config/woow-tailscale-gateway/gateway.env"
if [[ -e "$installed_env" ]]; then [[ -f "$installed_env" && ! -L "$installed_env" && "$(stat -c %a "$installed_env")" == 600 ]] || { echo 'refusing foreign installed gateway environment' >&2; exit 1; }; fi
image_present=false
if [[ "$purge" == true ]] && podman image inspect localhost/woow-tailscale-gateway:latest >/dev/null 2>&1; then
  image_json="$(podman image inspect localhost/woow-tailscale-gateway:latest)"
  jq -e --arg root "$ROOT" '.[0].Labels["org.woow-tailscale.project"]=="woow-tailscale-gateway" and .[0].Labels["org.woow-tailscale.role"]=="image" and .[0].Labels["org.woow-tailscale.managed-by"]=="woow-gateway-lifecycle" and .[0].Labels["org.woow-tailscale.checkout"]==$root' >/dev/null <<<"$image_json" || { echo 'refusing foreign image' >&2; exit 1; }
  iid="$(jq -r '.[0].Id' <<<"$image_json")"; image_present=true
fi
if [[ "$delete_node" == true ]]; then
  [[ -f runtime/gateway-node-id ]] || { echo 'persisted gateway node ID is absent' >&2; exit 1; }
  node="$(<runtime/gateway-node-id)"; [[ "$node" =~ ^[0-9]+$ ]] || { echo 'invalid persisted node ID' >&2; exit 1; }
  cfg="$(python3 scripts/gateway_config.py parse-env .env.gateway)"; hs="$(jq -r .HEADSCALE_CONTAINER <<<"$cfg")"
  nodes="$(mktemp runtime/.nodes.XXXXXX)"; chmod 600 "$nodes"; podman exec "$hs" headscale nodes list --output json >"$nodes"
  count="$(jq --argjson id "$node" '[.[] | select(.id==$id)]|length' "$nodes")"; rm -f "$nodes"; [[ "$count" == 1 ]] || { echo 'persisted node is not unique in Headscale' >&2; exit 1; }
fi
before="$(mktemp "${XDG_RUNTIME_DIR:-/tmp}/woow-remove-before.XXXXXX")"; after="$(mktemp "${XDG_RUNTIME_DIR:-/tmp}/woow-remove-after.XXXXXX")"; chmod 600 "$before" "$after"
cleanup_snapshots(){ rc=$?; trap - EXIT INT TERM; rm -f "$before" "$after"; exit "$rc"; }
trap cleanup_snapshots EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
snapshot(){ own=''; if podman container inspect woow-tailscale-gateway >/dev/null 2>&1; then own="$(podman container inspect --format '{{.Id}}' woow-tailscale-gateway)"; else python3 scripts/resource_ownership.py assert-container-absent "$ROOT"; fi; all="$(podman ps -aq)"; keep=(); for id in $all; do [[ "$id" == "$own" ]] || keep+=("$id"); done; if ((${#keep[@]})); then podman inspect "${keep[@]}"; else printf '[]\n'; fi; }
snapshot >"$before"
container_present=false; if podman container inspect woow-tailscale-gateway >/dev/null 2>&1; then container_present=true; else python3 scripts/resource_ownership.py assert-container-absent "$ROOT"; fi
if [[ -e "$unit" || -n "$fragment" ]]; then
  systemctl --user disable --now woow-tailscale-gateway.service >/dev/null
fi
if [[ "$container_present" == true ]]; then
  podman rm -f woow-tailscale-gateway >/dev/null
fi
python3 scripts/resource_ownership.py assert-container-absent "$ROOT"
if [[ -e "$unit" ]]; then rm -- "$unit"; fi
rm -f "$installed_env"; rmdir "$HOME/.config/woow-tailscale-gateway" 2>/dev/null || true
systemctl --user daemon-reload
if [[ "$delete_node" == true ]]; then
  podman exec "$hs" headscale --force nodes delete --identifier "$node"
  nodes="$(mktemp runtime/.nodes.XXXXXX)"; chmod 600 "$nodes"
  podman exec "$hs" headscale nodes list --output json >"$nodes"
  python3 scripts/headscale_json.py assert-node-id-absent "$nodes" "$node"
  : >"$nodes"; rm -f "$nodes"
  rm -f runtime/gateway-node-id runtime/gateway-self-id runtime/gateway-enrollment-id
fi
if [[ "$purge" == true ]]; then
  if podman volume inspect woow-tailscale-gateway-state >/dev/null 2>&1; then
    python3 scripts/resource_ownership.py check-volume "$ROOT"
    podman volume rm woow-tailscale-gateway-state >/dev/null
  else
    python3 scripts/resource_ownership.py assert-volume-absent "$ROOT"
  fi
  python3 scripts/resource_ownership.py assert-volume-absent "$ROOT"
  if [[ "$image_present" == true ]]; then
    users="$(podman ps -aq --filter "ancestor=$iid")"
    if [[ -z "$users" ]]; then podman image rm "$iid" >/dev/null; else echo 'Retaining image used by another container.' >&2; fi
  fi
fi
snapshot >"$after"
python3 - "$before" "$after" <<'PY'
import json,sys
def norm(p):
 d=json.load(open(p));return {x['Id']:{'name':x.get('Name'),'running':x.get('State',{}).get('Running'),'health':x.get('State',{}).get('Health',{}).get('Status')} for x in d}
if norm(sys.argv[1])!=norm(sys.argv[2]):raise SystemExit('unrelated container state changed')
PY
rm -f "$before" "$after"
trap - EXIT INT TERM
if [[ "$purge" == true ]]; then echo 'Gateway removed; persistent state purged.'; else echo 'Gateway removed; persistent state retained.'; fi
