#!/usr/bin/env bash
# Read-only aggregate verification (except explicit Podman healthcheck evidence file).
set -uo pipefail
umask 077
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"; cd "$ROOT"
C=woow-tailscale-gateway; V=woow-tailscale-gateway-state; U=woow-tailscale-gateway.service
failures=0
pass(){ printf 'PASS: %s\n' "$1"; }
fail(){ printf 'FAIL: %s\n' "$1" >&2; failures=$((failures+1)); }
check(){ local name="$1"; shift; if "$@" >/dev/null 2>&1; then pass "$name"; else fail "$name"; fi; }
check 'strict gateway configuration' python3 scripts/gateway_config.py parse-env .env.gateway
uid="$(id -u)"
owned_mode(){ [[ -f "$1" && ! -L "$1" && "$(stat -c %a "$1" 2>/dev/null)" == "$2" && "$(stat -c %u "$1" 2>/dev/null)" == "$uid" ]]; }
[[ -d runtime && ! -L runtime && "$(stat -c %a runtime 2>/dev/null)" == 700 && "$(stat -c %u runtime 2>/dev/null)" == "$uid" ]] && pass 'runtime directory ownership mode' || fail 'runtime directory ownership mode'
owned_mode .env.gateway 600 && pass '.env.gateway ownership mode' || fail '.env.gateway ownership mode'
owned_mode runtime/gateway.env 600 && pass 'runtime environment mode' || fail 'runtime environment mode'
owned_mode runtime/gateway-self-id 600 && pass 'persisted Self.ID ownership mode' || fail 'persisted Self.ID ownership mode'
owned_mode runtime/gateway-node-id 600 && pass 'persisted Headscale node ownership mode' || fail 'persisted Headscale node ownership mode'
owned_mode runtime/gateway-enrollment-id 600 && pass 'persisted enrollment ID ownership mode' || fail 'persisted enrollment ID ownership mode'
owned_mode "$HOME/.config/woow-tailscale-gateway/gateway.env" 600 && pass 'installed environment mode' || fail 'installed environment mode'
owned_mode "$HOME/.config/systemd/user/$U" 600 && grep -Fxq '# Generated by woow-tailscale-gateway; do not edit.' "$HOME/.config/systemd/user/$U" && pass 'installed generated unit' || fail 'installed generated unit'
version="$(podman version --format '{{.Client.Version}}' 2>/dev/null || true)"
[[ -n "$version" && "$(printf '%s\n' 4.9.3 "$version" | sort -V | head -1)" == 4.9.3 ]] && pass 'Podman >= 4.9.3' || fail 'Podman >= 4.9.3'
config="$(python3 scripts/gateway_config.py parse-env .env.gateway 2>/dev/null || echo '{}')"; hs="$(jq -r '.HEADSCALE_CONTAINER // "headscale"' <<<"$config")"; hostname="$(jq -r '.GATEWAY_HOSTNAME // empty' <<<"$config")"
hv="$(podman exec "$hs" headscale version 2>/dev/null || true)"; [[ "$hv" =~ (^|[[:space:]])v?0\.29\.3($|[[:space:]]) ]] && pass 'Headscale exactly 0.29.3' || fail 'Headscale exactly 0.29.3'
check 'container exact ownership' python3 scripts/resource_ownership.py check-container "$ROOT"
check 'volume exact ownership' python3 scripts/resource_ownership.py check-volume "$ROOT"
image="$(podman image inspect localhost/woow-tailscale-gateway:latest 2>/dev/null || echo '[]')"
if jq -e --arg root "$ROOT" '.[0].Labels["org.woow-tailscale.project"]=="woow-tailscale-gateway" and .[0].Labels["org.woow-tailscale.role"]=="image" and .[0].Labels["org.woow-tailscale.managed-by"]=="woow-gateway-lifecycle" and .[0].Labels["org.woow-tailscale.checkout"]==$root' >/dev/null 2>&1 <<<"$image"; then pass 'image exact ownership'; else fail 'image exact ownership'; fi
observed_expected_image="$(jq -r '.[0].Id // empty' <<<"$image" 2>/dev/null)"
expected_image=''
if expected_image="$(python3 scripts/image_id.py "$observed_expected_image" 2>/dev/null)" && grep -Fq -- " $expected_image" "$HOME/.config/systemd/user/$U" 2>/dev/null; then pass 'unit immutable image identity'; else fail 'unit immutable image identity'; fi
check 'unit enabled' systemctl --user is-enabled --quiet "$U"
check 'unit active' systemctl --user is-active --quiet "$U"
[[ "$(systemctl --user show -p Restart --value "$U" 2>/dev/null)" == always ]] && pass 'unit restart policy' || fail 'unit restart policy'
inspect="$(podman container inspect "$C" 2>/dev/null || echo '[]')"
observed_running_image="$(jq -r '.[0].Image // empty' <<<"$inspect" 2>/dev/null)"
running_image=''
if [[ -n "$expected_image" ]] && running_image="$(python3 scripts/image_id.py "$observed_running_image" 2>/dev/null)" && [[ "$running_image" == "$expected_image" ]]; then pass 'running immutable image identity'; else fail 'running immutable image identity'; fi
check_runtime='.[0] | .State.Running==true and .HostConfig.NetworkMode=="host" and ((.HostConfig.PortBindings // {})|length==0) and ((.HostConfig.CapAdd // [])|length==0) and ((.HostConfig.Devices // [])|length==0) and ((.Config.Env // [])|any(.=="TS_GATEWAY_MODE=true")) and ((.Config.Env // [])|any(.=="TS_USERSPACE_NETWORKING=true")) and ((.Config.Env // [])|any(.=="TS_WEB_UI=false")) and ((.Config.Env // [])|any(.=="TS_SERVE_TCP_18081=127.0.0.1:18081")) and ((.Config.Env // [])|any(.=="TS_SERVE_TCP_18069=127.0.0.1:18069")) and ((.Config.Env // [])|all((startswith("TS_AUTHKEY") or test("^TS_(ACCEPT_ROUTES|ADVERTISE_ROUTES|ADVERTISE_EXIT_NODE|SNAT_SUBNET_ROUTES|STATEFUL_FILTERING|EXIT_NODE)="))|not)) and ((.Mounts // [])|all((.Destination // "")|startswith("/run/secrets/")|not)) and ([.Mounts[]? | select(.Destination=="/var/lib/tailscale" and .Name=="woow-tailscale-gateway-state")]|length==1)'
if jq -e "$check_runtime" >/dev/null 2>&1 <<<"$inspect"; then pass 'host/userspace security posture'; else fail 'host/userspace security posture'; fi
check 'explicit container healthcheck' podman healthcheck run "$C"
inspect="$(podman container inspect "$C" 2>/dev/null || echo '[]')"
health="$(jq -r '.[0].State.Health.Status // empty' <<<"$inspect" 2>/dev/null)"; [[ "$health" == healthy ]] && pass 'container healthy state' || fail 'container healthy state'
status="$(podman exec "$C" tailscale status --json 2>/dev/null || echo '{}')"
node_id="$(jq -r '.Self.ID // empty' <<<"$status" 2>/dev/null)"; self_ip="$(jq -r '.Self.TailscaleIPs[0] // empty' <<<"$status" 2>/dev/null)"
expected_self="$(cat runtime/gateway-self-id 2>/dev/null || true)"
if [[ -n "$expected_self" && "$node_id" == "$expected_self" ]] && jq -e --arg h "$hostname" '.BackendState=="Running" and ((.Self.HostName // .Self.DNSName | rtrimstr("."))==$h)' >/dev/null 2>&1 <<<"$status"; then pass 'backend, hostname, and exact persisted Self.ID'; else fail 'backend, hostname, and exact persisted Self.ID'; fi
headscale_data="$(mktemp runtime/.headscale-check.XXXXXX)"; chmod 600 "$headscale_data"
if [[ -n "$self_ip" ]] && podman exec "$hs" headscale nodes list --output json >"$headscale_data" 2>/dev/null && matched_node="$(python3 scripts/headscale_json.py find-node "$headscale_data" "$hostname" --ip "$self_ip" 2>/dev/null)" && [[ "$matched_node" == "$(cat runtime/gateway-node-id 2>/dev/null)" ]]; then pass 'disambiguated Headscale node identity'; else fail 'disambiguated Headscale node identity'; fi
: >"$headscale_data"
enrollment_id="$(cat runtime/gateway-enrollment-id 2>/dev/null || true)"
if [[ "$enrollment_id" =~ ^[0-9]+$ ]] && podman exec "$hs" headscale preauthkeys list --output json >"$headscale_data" 2>/dev/null && python3 scripts/headscale_json.py assert-preauth-id-absent "$headscale_data" "$enrollment_id" >/dev/null 2>&1; then pass 'gateway enrollment key ID is absent'; else fail 'gateway enrollment key ID is absent'; fi
: >"$headscale_data"; rm -f "$headscale_data"
serve="$(podman exec "$C" tailscale serve status --json 2>/dev/null || echo '{}')"
if jq -e 'type=="object" and (((keys-["TCP","Web"])|length)==0) and ((.Web // {})=={}) and (.TCP|keys|sort)==["18069","18081"] and .TCP["18081"].TCPForward=="127.0.0.1:18081" and .TCP["18069"].TCPForward=="127.0.0.1:18069"' >/dev/null 2>&1 <<<"$serve"; then pass 'exact Serve listeners and namespace'; else fail 'exact Serve listeners and namespace'; fi
services='{}'
for spec in 'npm:18081' 'odoo:18069'; do name="${spec%:*}"; port="${spec#*:}"; code="$(curl -sS -o /dev/null --max-time 5 -w '%{http_code}' "http://127.0.0.1:$port/" 2>/dev/null || echo 000)"; if [[ "$code" =~ ^[1-4][0-9][0-9]$ ]]; then pass "$name loopback HTTP ($code)"; services="$(jq -c --arg n "$name" --arg c "$code" '.+{($n):$c}' <<<"$services")"; else fail "$name loopback HTTP"; fi; done
check 'Headscale health' podman exec "$hs" headscale health
if find runtime -maxdepth 1 -type f \( -name '.*preauth*' -o -name '.*enrollment*' \) -print -quit | grep -q .; then fail 'no temporary enrollment artifacts'; else pass 'no temporary enrollment artifacts'; fi
secret_material="$(mktemp runtime/.verification-scan.XXXXXX)"
{ printf '%s\n' "$inspect"; systemctl --user cat "$U" 2>/dev/null; journalctl --user-unit "$U" --since '24 hours ago' --no-pager 2>/dev/null; } >"$secret_material"
if python3 scripts/secret_scan.py "$ROOT" --runtime-evidence "$secret_material" >/dev/null 2>&1; then pass 'no key material in repository/runtime/inspect/unit/journal'; else fail 'no key material in repository/runtime/inspect/unit/journal'; fi
: >"$secret_material"; rm -f "$secret_material"
mkdir -p runtime; chmod 700 runtime
python3 - "$ROOT/runtime/last-verification.json" "$node_id" "$services" "$failures" <<'PY'
import json,os,sys,tempfile,datetime,subprocess
p,self_id,services,failures=sys.argv[1:]; data={'timestamp':datetime.datetime.now(datetime.timezone.utc).isoformat(),'commit':subprocess.run(['git','rev-parse','HEAD'],text=True,capture_output=True).stdout.strip(),'self_id':self_id,'services':json.loads(services),'live_test_status':'not-run','failures':int(failures)}
fd,t=tempfile.mkstemp(prefix='.verification.',dir=os.path.dirname(p));os.fchmod(fd,0o600)
with os.fdopen(fd,'w') as f:json.dump(data,f,sort_keys=True);f.write('\n')
os.replace(t,p)
PY
(( failures == 0 )) || exit 1
